In [1]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [2]:
heart=pd.read_csv("heart_disease_dataset.csv")
heart.dropna(inplace=True)

In [3]:
heart.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.438944    0.679868    3.158416  131.689769  246.693069    0.148515   
std      9.038662    0.467299    0.960126   17.599748   51.776918    0.356198   
min     29.000000    0.000000    1.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    3.000000  120.000000  211.000000    0.000000   
50%     56.000000    1.000000    3.000000  130.000000  241.000000    0.000000   
75%     61.000000    1.000000    4.000000  140.000000  275.000000    0.000000   
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope  \
count  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.990099  149.607261    0.326733    1.039604    1.600660   
std      0.994971   22.875003    0.469794    1.161075    0.616226   
min      0.000000   71.000000    0.000000    0.000000    1.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000   
50%      1.000000  153.000000    0.000000    0.800000    2.000000   
75%      2.000000  166.000000    1.000000    1.600000    2.000000   
max      2.000000  202.000000    1.000000    6.200000    3.000000   

                  ca           thal         num  
count     303.000000     303.000000  303.000000  
mean    -1319.468647    -655.363036    0.458746  
std     11432.566205    8111.366638    0.499120  
min   -100000.000000 -100000.000000    0.000000  
25%         0.000000       3.000000    0.000000  
50%         0.000000       3.000000    0.000000  
75%         1.000000       7.000000    1.000000  
max         3.000000       7.000000    1.000000

In [4]:
x=heart.iloc[:, 0:13].values
y=heart['num'].values

Выводим 5 первых строчек датасета

In [5]:
heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  num  
0   0     6    0  
1   3     3    1  
2   2     7    1  
3   0     3    0  
4   0     3    0

Менять символы на цифры не требуется, все данные и так являются числовыми значениями

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test =train_test_split(x, y, test_size=0.3, random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)

In [8]:
x_train[:5], x_train_std[:5]

(array([[ 62. ,   1. ,   2. , 120. , 281. ,   0. ,   2. , 103. ,   0. ,
           1.4,   2. ,   1. ,   7. ],
        [ 59. ,   1. ,   4. , 140. , 177. ,   0. ,   0. , 162. ,   1. ,
           0. ,   1. ,   1. ,   7. ],
        [ 61. ,   1. ,   4. , 148. , 203. ,   0. ,   0. , 161. ,   0. ,
           0. ,   1. ,   1. ,   7. ],
        [ 61. ,   0. ,   4. , 130. , 330. ,   0. ,   2. , 169. ,   0. ,
           0. ,   1. ,   0. ,   3. ],
        [ 51. ,   1. ,   3. , 125. , 245. ,   1. ,   2. , 166. ,   0. ,
           2.4,   2. ,   0. ,   3. ]]),
 array([[ 0.839319  ,  0.66496381, -1.20851058, -0.72157478,  0.75916833,
         -0.40599897,  1.08892903, -2.14731109, -0.68718427,  0.28192251,
          0.60016507,  0.0688961 ,  0.0978092 ],
        [ 0.51697185,  0.66496381,  0.88295263,  0.45923458, -1.38977805,
         -0.40599897, -0.93609688,  0.52891122,  1.45521375, -0.88508726,
         -0.99027236,  0.0688961 ,  0.0978092 ],
        [ 0.73186995,  0.66496381,  0.88295263,  0.931

In [9]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=100.0, random_state=1)
lr.fit(x_train_std, y_train)

LogisticRegression(C=100.0, random_state=1)

In [10]:
lr.predict_proba(x_test_std[:5, :])

array([[0.99615884, 0.00384116],
       [0.16442411, 0.83557589],
       [0.13605361, 0.86394639],
       [0.18639153, 0.81360847],
       [0.72981837, 0.27018163]])

In [11]:
lr.predict_proba(x_test_std[:5, :]).sum(axis=1)

array([1., 1., 1., 1., 1.])

In [12]:
y_test[:5]

array([0, 0, 1, 0, 1], dtype=int64)

In [13]:
lr.predict_proba(x_test_std[:5, :]).argmax(axis=1)

array([0, 1, 1, 1, 0], dtype=int64)

In [14]:
lr.predict(x_test_std[0, :].reshape(1, -1))

array([0], dtype=int64)

In [15]:
x_test_std[0, :]

array([-2.16925442, -1.50384124, -1.20851058, -0.83965571, -0.70790083,
       -0.40599897, -0.93609688,  1.88970222, -0.68718427, -0.30158238,
       -0.99027236,  0.06875015,  0.09739544])

In [16]:
x_test_std[0, :].reshape(1, -1)

array([[-2.16925442, -1.50384124, -1.20851058, -0.83965571, -0.70790083,
        -0.40599897, -0.93609688,  1.88970222, -0.68718427, -0.30158238,
        -0.99027236,  0.06875015,  0.09739544]])

In [17]:
y_pred = lr.predict(x_test_std)

# Линейная классификация

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.70      0.69        47
           1       0.67      0.64      0.65        44

    accuracy                           0.67        91
   macro avg       0.67      0.67      0.67        91
weighted avg       0.67      0.67      0.67        91



Все методы оценки показывают что результат далек от иделала, возможно это связанно с маленьким количеством данных датасета или данный метод плохо подходит для данной задачи, но тем не менее результат есть, и он около 0.7 а значит в большинсве случаев результат предсказания верный

#  Машина опорных векторов

In [19]:
from sklearn.svm import SVC

svm = SVC(kernel='linear', C=1.0, random_state=1)
svm.fit(x_train_std, y_train)

SVC(kernel='linear', random_state=1)

In [20]:
y_pred_svm = svm.predict(x_test_std)

In [21]:
print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

           0       0.68      0.77      0.72        47
           1       0.71      0.61      0.66        44

    accuracy                           0.69        91
   macro avg       0.69      0.69      0.69        91
weighted avg       0.69      0.69      0.69        91



По данным оценки результат стал заметно лучше, но так же не близок к иделау f1-score говорит что для значений целевой переменной 0 результат лучше и равен 0.72

# Нелинейная классификация

In [22]:
svm_rbf = SVC(kernel='rbf', random_state=1, gamma=0.10, C=10.0)
svm_rbf.fit(x_train_std, y_train)

SVC(C=10.0, gamma=0.1, random_state=1)

In [23]:
y_pred_svm_rbf = svm_rbf.predict(x_test_std)

In [24]:
print(classification_report(y_test, y_pred_svm_rbf))

              precision    recall  f1-score   support

           0       0.74      0.72      0.73        47
           1       0.71      0.73      0.72        44

    accuracy                           0.73        91
   macro avg       0.73      0.73      0.73        91
weighted avg       0.73      0.73      0.73        91



Результат стал еще лучше, что демонстрируют все оценочные методы, их результаты похожи

# Деревья принятия решений

In [25]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(criterion='gini', max_depth=4,
                             random_state=1)
tree.fit(x_train_std, y_train)

DecisionTreeClassifier(max_depth=4, random_state=1)

In [26]:
y_pred_tree = tree.predict(x_test_std)

In [27]:
print(classification_report(y_test, y_pred_tree))

              precision    recall  f1-score   support

           0       0.75      0.85      0.80        47
           1       0.82      0.70      0.76        44

    accuracy                           0.78        91
   macro avg       0.79      0.78      0.78        91
weighted avg       0.78      0.78      0.78        91



Результат стал достаточно хорошим большинство ответов, являются правильными, хороший результат правильных ответов являющимися верными  0.82. Все методы показали что метод обучения хорошо подходит для данной задачи 

# Метод ближайших соседей

In [28]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn.fit(x_train_std, y_train)

y_pred_knn = knn.predict(x_test_std)
print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.70      0.81      0.75        47
           1       0.76      0.64      0.69        44

    accuracy                           0.73        91
   macro avg       0.73      0.72      0.72        91
weighted avg       0.73      0.73      0.72        91



Также большинство результатов оказываются правильными 

По итогам для данной задачи лучше всего подошел метод дерева принятия решений показав значительно лучший результат по всем оценочным методам