In [1]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [2]:
voting=pd.read_csv("congressional_voting_dataset.csv")
# Удаляем строки с вопросительными знаками
voting = voting[(voting != '?')]
# Удаляем строки с пустыми значениями
voting.dropna(inplace=True)

In [3]:
voting.describe()

handicapped_infants water_project_cost_sharing  \
count                  232                        232   
unique                   2                          2   
top                      n                          n   
freq                   136                        125   

       adoption_of_the_budget_resolution physician_fee_freeze el_salvador_aid  \
count                                232                  232             232   
unique                                 2                    2               2   
top                                    y                    n               y   
freq                                 123                  119             128   

       religious_groups_in_schools anti_satellite_test_ban  \
count                          232                     232   
unique                           2                       2   
top                              y                       y   
freq                           149                     124   

       aid_to_nicaraguan_contras mx_missile immigration  \
count                        232        232         232   
unique                         2          2           2   
top                            y          n           y   
freq                         119        119         128   

       synfuels_corporation_cutback education_spending superfund_right_to_sue  \
count                           232                232                    232   
unique                            2                  2                      2   
top                               n                  n                      y   
freq                            152                124                    127   

       crime duty_free_exports export_administration_act_south_africa  \
count    232               232                                    232   
unique     2                 2                                      2   
top        y                 n                                      y   
freq     149               146                                    189   

       political_party  
count              232  
unique               2  
top           democrat  
freq               124

In [4]:
x=voting.iloc[:, 0:16].values
y=voting['political_party'].values

Выводим первые 5 строк датасета

In [5]:
voting.head()

handicapped_infants water_project_cost_sharing  \
5                    n                          y   
8                    n                          y   
19                   y                          y   
23                   y                          y   
25                   y                          n   

   adoption_of_the_budget_resolution physician_fee_freeze el_salvador_aid  \
5                                  y                    n               y   
8                                  n                    y               y   
19                                 y                    n               n   
23                                 y                    n               n   
25                                 y                    n               n   

   religious_groups_in_schools anti_satellite_test_ban  \
5                            y                       n   
8                            y                       n   
19                           n                       y   
23                           n                       y   
25                           n                       y   

   aid_to_nicaraguan_contras mx_missile immigration  \
5                          n          n           n   
8                          n          n           n   
19                         y          y           n   
23                         y          y           n   
25                         y          y           y   

   synfuels_corporation_cutback education_spending superfund_right_to_sue  \
5                             n                  n                      y   
8                             n                  y                      y   
19                            y                  n                      n   
23                            n                  n                      n   
25                            n                  n                      n   

   crime duty_free_exports export_administration_act_south_africa  \
5      y                 y                                      y   
8      y                 n                                      y   
19     n                 y                                      y   
23     n                 y                                      y   
25     n                 y                                      y   

   political_party  
5         democrat  
8       republican  
19        democrat  
23        democrat  
25        democrat

выводим 5 значений х

In [6]:
x[:5]

array([['n', 'y', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'n', 'y',
        'y', 'y', 'y'],
       ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y',
        'y', 'n', 'y'],
       ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'n',
        'n', 'y', 'y'],
       ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n',
        'n', 'y', 'y'],
       ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n',
        'n', 'y', 'y']], dtype=object)

меняем символы на цифры

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

le = LabelEncoder()
le.fit(y)
y = le.transform(y)


enc = OrdinalEncoder()
enc.fit(x)
x = enc.transform(x)

выводим новые х

In [8]:
x[:5]

array([[0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1.],
       [1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1.],
       [1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1.],
       [1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1.]])

In [ ]:
выводим новые у

In [9]:
y[:5]

array([0, 1, 0, 0, 0])

In [10]:
voting_pred_names = le.classes_
voting_pred_names

array(['democrat', 'republican'], dtype=object)

In [11]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test =train_test_split(x, y, test_size=0.3, random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)

In [13]:
x_train[:5], x_train_std[:5]

(array([[0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1.],
        [0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0.],
        [0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1.]]),
 array([[-0.81859825, -0.94006432,  0.91701095, -0.94006432, -1.10416397,
          0.72684378,  0.89442719,  0.96362411,  1.063757  ,  0.97560608,
         -0.71695097, -0.92847669, -1.063757  ,  0.78740079, -0.78740079,
          0.47673129],
        [-0.81859825,  1.063757  , -1.09049951,  1.063757  ,  0.90566259,
          0.72684378, -1.11803399, -1.03774904, -0.94006432,  0.97560608,
         -0.71695097,  1.07703296,  0.94006432,  0.78740079, -0.78740079,
          0.47673129],
        [ 1.22160046,  1.063757  ,  0.91701095, -0.94006432, -1.10416397,
         -1.37581145,  0.89442719,  0.96362411,  1.063757  , -1.

In [14]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=100.0, random_state=1)
lr.fit(x_train_std, y_train)

LogisticRegression(C=100.0, random_state=1)

In [15]:
lr.predict_proba(x_test_std[:5, :])

array([[9.99999999e-01, 1.15775948e-09],
       [3.33363057e-06, 9.99996666e-01],
       [9.99999991e-01, 8.85951930e-09],
       [3.84663889e-01, 6.15336111e-01],
       [4.25885271e-07, 9.99999574e-01]])

In [16]:
lr.predict_proba(x_test_std[:5, :]).sum(axis=1)

array([1., 1., 1., 1., 1.])

In [17]:
y_test[:5]

array([0, 1, 0, 1, 1])

In [18]:
lr.predict_proba(x_test_std[:5, :]).argmax(axis=1)

array([0, 1, 0, 1, 1], dtype=int64)

In [19]:
lr.predict(x_test_std[0, :].reshape(1, -1))

array([0])

In [20]:
x_test_std[0, :]

array([ 1.22160046,  1.063757  ,  0.91701095, -0.94006432, -1.10416397,
       -1.37581145,  0.89442719,  0.96362411,  1.063757  , -1.02500386,
       -0.71695097, -0.92847669, -1.063757  , -1.27000127, -0.78740079,
        0.47673129])

In [21]:
x_test_std[0, :].reshape(1, -1)

array([[ 1.22160046,  1.063757  ,  0.91701095, -0.94006432, -1.10416397,
        -1.37581145,  0.89442719,  0.96362411,  1.063757  , -1.02500386,
        -0.71695097, -0.92847669, -1.063757  , -1.27000127, -0.78740079,
         0.47673129]])

In [22]:
y_pred = lr.predict(x_test_std)

In [23]:
len(voting_pred_names)

2

# Линейная классификация

In [24]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred, target_names=voting_pred_names))

              precision    recall  f1-score   support

    democrat       0.91      0.94      0.93        34
  republican       0.94      0.92      0.93        36

    accuracy                           0.93        70
   macro avg       0.93      0.93      0.93        70
weighted avg       0.93      0.93      0.93        70



In [ ]:
По всем метрикам качества можно увидеть, что результат близок к отличному,  precision и recall позволяют увидеть что верно определеных верных значений 0.91 и 0.94

#  Машина опорных векторов

In [25]:
from sklearn.svm import SVC

svm = SVC(kernel='linear', C=1.0, random_state=1)
svm.fit(x_train_std, y_train)

SVC(kernel='linear', random_state=1)

In [26]:
y_pred_svm = svm.predict(x_test_std)

In [27]:
print(classification_report(y_test, y_pred_svm, target_names=voting_pred_names))

              precision    recall  f1-score   support

    democrat       0.97      0.91      0.94        34
  republican       0.92      0.97      0.95        36

    accuracy                           0.94        70
   macro avg       0.94      0.94      0.94        70
weighted avg       0.94      0.94      0.94        70



Снова по всем метрикам качества можно увидеть, что результат близок к отличному, результат стал чуть лучше

# Нелинейная классификация

In [28]:
svm_rbf = SVC(kernel='rbf', random_state=1, gamma=0.10, C=10.0)
svm_rbf.fit(x_train_std, y_train)

SVC(C=10.0, gamma=0.1, random_state=1)

In [29]:
y_pred_svm_rbf = svm_rbf.predict(x_test_std)

In [30]:
print(classification_report(y_test, y_pred_svm_rbf, target_names=voting_pred_names))

              precision    recall  f1-score   support

    democrat       0.92      0.97      0.94        34
  republican       0.97      0.92      0.94        36

    accuracy                           0.94        70
   macro avg       0.94      0.94      0.94        70
weighted avg       0.94      0.94      0.94        70



Снова по всем метрикам качества можно увидеть, что результат близок к отличному, результат примерно такой-же

# Деревья принятия решений

In [31]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(criterion='gini', max_depth=4,
                             random_state=1)
tree.fit(x_train_std, y_train)

DecisionTreeClassifier(max_depth=4, random_state=1)

In [32]:
y_pred_tree = tree.predict(x_test_std)

In [33]:
print(classification_report(y_test, y_pred_tree, target_names=voting_pred_names))

              precision    recall  f1-score   support

    democrat       0.87      0.97      0.92        34
  republican       0.97      0.86      0.91        36

    accuracy                           0.91        70
   macro avg       0.92      0.92      0.91        70
weighted avg       0.92      0.91      0.91        70



Снова по всем метрикам качества можно увидеть, что результат близок к отличному, результат хуже, но все еще является очень хорошим

# Метод ближайших соседей

In [34]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn.fit(x_train_std, y_train)

y_pred_knn = knn.predict(x_test_std)
print(classification_report(y_test, y_pred_knn, target_names=voting_pred_names))

              precision    recall  f1-score   support

    democrat       0.91      0.94      0.93        34
  republican       0.94      0.92      0.93        36

    accuracy                           0.93        70
   macro avg       0.93      0.93      0.93        70
weighted avg       0.93      0.93      0.93        70



Снова по всем метрикам качества можно увидеть, что результат близок к отличному, результат очень хороший и сравним с предыдущими методами.
В итоге лучшей моделью с небольшой разницей для данного датасета стал метод Машины опорных векторов и метод нелинейной классификации